name: app_environment
channels:
  - snowflake
dependencies:
  - anyio=*
  - distro=*
  - httpx=*
  - jiter=*
  - pydantic=*
  - sniffio=*
  - typing-extensions=*
  - langsmith=*
  - tenacity=*
  - jsonpatch=*
  - pyyaml=*
  - packaging=*
  - langchain-core=*
  - orjson=*
